### ISSUE TITLE
Considerar separar los imports de librerías y frameworks (poner arriba) de los imports del propio proyecto (abajo), separados por un espacio y ordenados de mayor a menor cantidad de texto, tipo:

### ISSUE THREAD

**Issue by eatskolnikov** [Streamelopers/opus-api#53]
Considerar separar los imports de librerías y frameworks (poner arriba) de los imports del propio proyecto (abajo), separados por un espacio y ordenados de mayor a menor cantidad de texto, tipo:
```Typescript
import { ConfigModule } from "@nestjs/config";
import { Module } from "@nestjs/common";

import { CompaniesModule } from "./companies/companies.module";
import { UsersModule } from "./users/users.module";
```

_Originally posted by @JeffreyArt1 in https://github.com/Streamelopers/opus-api/pull/50#r720272715_

**Comment by Jadhielv** [comment]
Hey! @eatskolnikov, me parece que ya @MarluanEspiritusanto completó este issue en PR -> [Estandarizando la estructura y documentación del proyecto](https://github.com/Streamelopers/opus-api/pull/54)
